[package]
name = "day_1"
version = "0.1.0"
edition = "2021"

[dependencies]
aochelpers = "0.7.1"
nom = "7.1.3"
regex = "1.11.1"

[lib]
name = "day_1"
path = "src/lib.rs"

[dev-dependencies]
divan = "0.1.16"

[[bench]]
name = "aoc"
harness = false
