[package]
name = "day_2"
version = "0.1.0"
edition = "2021"

[dependencies]
aochelpers = "0.7.1"
itertools = "0.13.0"
miette = "7.4.0"
nom = "7.1.3"
regex = "1.11.1"

[lib]
name = "day_2"
path = "src/lib.rs"

[dev-dependencies]
divan = "0.1.16"

[[bench]]
name = "aoc"
harness = false
