[package]
name = "day_4"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = "7.1.3"
itertools = "0.13.0"
glam = "0.29.2"

[lib]
name = "day_4"
path = "src/lib.rs"

[dev-dependencies]
divan = "0.1.16"

[[bench]]
name = "aoc"
harness = false
